import { useState } from "react";
//components
import { Row, Col } from "react-bootstrap";
import { UiContainer } from "@/customBootstrap";
import { TitleH3, TitleH6 } from "@/ui/Text";
import ListTickets from "@/tickets/ListTickets";
const LIST_TEST = [
  {
    id: 850,
    tracking_number: "794669658015",
    company_id: 18,
    ticket_status_id: 1,
    ticket_status_name: "pending",
    ticket_status_color: "#FFB136",
    ticket_type_id: 8,
    ticket_type_name: "delay",
    carrier_id: null,
    shipment_id: 13100,
    credit_id: null,
    warehouse_package_id: null,
    data: '{"tracking_number": "794669658015"}',
    comments:
      "Package Description: \nContent description: \nAddress references: zfsdF",
    file_quantity: 1,
    created_by: 27,
    created_at: "2021-10-01 15:55:06",
    updated_at: null,
    last_comment: {},
    files: [
      {
        id: "1571",
        name: "Content invoice",
        description: "problem-delay-invoice",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/794669658015_delay_invoice.jpeg",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-10-01 20:55:06",
      },
    ],
  },
  {
    id: 812,
    tracking_number: null,
    company_id: 18,
    ticket_status_id: 1,
    ticket_status_name: "pending",
    ticket_status_color: "#FFB136",
    ticket_type_id: 9,
    ticket_type_name: "payment_pending",
    carrier_id: null,
    shipment_id: null,
    credit_id: null,
    warehouse_package_id: null,
    data: '{"payment_method_name": "conekta","payment_method_description": "Conekta USA","payment_method_id": "42","bank_account": "ord_2qSWgvozs5VJCZ7pJ"}',
    comments: "mi comentario",
    file_quantity: 2,
    created_by: 27,
    created_at: "2021-09-13 15:36:57",
    updated_at: null,
    last_comment: {},
    files: [
      {
        id: "1531",
        name: "Payment Receipt",
        description: "payment-pending-receipt",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/clients/payments/18_20210913T203602.png",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-09-13 20:36:58",
      },
      {
        id: "1532",
        name: "otro",
        description: "additional-file",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/clients/payments/18_additional_file_20210913T203636.png",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-09-13 20:36:58",
      },
    ],
  },
  {
    id: 674,
    tracking_number: null,
    company_id: 18,
    ticket_status_id: 1,
    ticket_status_name: "pending",
    ticket_status_color: "#FFB136",
    ticket_type_id: 9,
    ticket_type_name: "payment_pending",
    carrier_id: null,
    shipment_id: null,
    credit_id: null,
    warehouse_package_id: null,
    data: '{"payment_method_name": "bank_transfer","payment_method_description": "Bank Transfer Mexico","payment_method_id": "2","bank_account": ""}',
    comments: "",
    file_quantity: 1,
    created_by: 27,
    created_at: "2021-08-17 11:55:32",
    updated_at: null,
    last_comment: {},
    files: [
      {
        id: "1225",
        name: "Payment Receipt",
        description: "payment-pending-receipt",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/clients/payments/18_20210817T165518.jpeg",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-17 16:55:32",
      },
    ],
  },
  {
    id: 662,
    tracking_number: "98368000413",
    company_id: 18,
    ticket_status_id: 2,
    ticket_status_name: "accepted",
    ticket_status_color: "#2ECC71",
    ticket_type_id: 12,
    ticket_type_name: "shipment_created_without_changes",
    carrier_id: null,
    shipment_id: 10754,
    credit_id: null,
    warehouse_package_id: null,
    data: '{"tracking_number": "98368000413"}',
    comments:
      "Características del paquete: \nCaracterísticas del contenido: \nCosto: \nFolio de Recolección: \nSucursal: ee",
    file_quantity: 3,
    created_by: 27,
    created_at: "2021-08-16 12:42:51",
    updated_at: "2021-08-16 12:48:07",
    last_comment: {
      type: "admin",
      status_id: 2,
      comment: "de",
      created_at: "2021-08-16 12:48:07",
    },
    files: [
      {
        id: "1195",
        name: "Evidencia de recolección firmada",
        description: "problem-inactive-pickup",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/98368000413_inactive_pickup.pdf",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-16 17:42:51",
      },
      {
        id: "1196",
        name: "Factura del contenido",
        description: "problem-inactive-invoice",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/98368000413_inactive_invoice.pdf",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-16 17:42:51",
      },
      {
        id: "1197",
        name: "Evidencia del empaque original",
        description: "problem-inactive-original",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/98368000413_inactive_original.pdf",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-16 17:42:51",
      },
    ],
  },
  {
    id: 661,
    tracking_number: "575dd924-b8e8-4d50-bfbf-fe290d88ce35",
    company_id: 18,
    ticket_status_id: 5,
    ticket_status_name: "follow_up",
    ticket_status_color: "#7e57c2",
    ticket_type_id: 8,
    ticket_type_name: "delay",
    carrier_id: null,
    shipment_id: 11244,
    credit_id: null,
    warehouse_package_id: null,
    data: '{"tracking_number": "575dd924-b8e8-4d50-bfbf-fe290d88ce35"}',
    comments:
      "Características del paquete: \nCaracterísticas del contenido: \nReferencias de la dirección:",
    file_quantity: 2,
    created_by: 27,
    created_at: "2021-08-16 12:42:25",
    updated_at: "2021-08-24 13:11:16",
    last_comment: {
      type: "client",
      status_id: 5,
      comment: "sfs",
      created_at: "2021-08-24 13:11:17",
    },
    files: [
      {
        id: "1193",
        name: "Factura del contenido",
        description: "problem-delay-invoice",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/575dd924-b8e8-4d50-bfbf-fe290d88ce35_delay_invoice.png",
        active: "0",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-16 17:42:25",
      },
      {
        id: "1194",
        name: "Evidencia del empaque original",
        description: "problem-delay-original",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/575dd924-b8e8-4d50-bfbf-fe290d88ce35_delay_original.pdf",
        active: "0",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-16 17:42:25",
      },
    ],
  },
  {
    id: 660,
    tracking_number: "421072870015",
    company_id: 18,
    ticket_status_id: 5,
    ticket_status_name: "follow_up",
    ticket_status_color: "#7e57c2",
    ticket_type_id: 12,
    ticket_type_name: "shipment_created_without_changes",
    carrier_id: null,
    shipment_id: 11827,
    credit_id: null,
    warehouse_package_id: null,
    data: '{"tracking_number": "421072870015"}',
    comments:
      "Características del paquete: \nCaracterísticas del contenido: \nCosto: \nFolio de Recolección: \nSucursal:",
    file_quantity: 4,
    created_by: 27,
    created_at: "2021-08-16 12:42:06",
    updated_at: "2021-08-24 15:10:26",
    last_comment: {
      type: "client",
      status_id: 5,
      comment: "Este también está chido.",
      created_at: "2021-08-24 15:10:27",
    },
    files: [
      {
        id: "1190",
        name: "Evidencia de recolección firmada",
        description: "problem-inactive-pickup",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/421072870015_inactive_pickup.png",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-16 17:42:06",
      },
      {
        id: "1191",
        name: "Factura del contenido",
        description: "problem-inactive-invoice",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/421072870015_inactive_invoice.png",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-16 17:42:06",
      },
      {
        id: "1192",
        name: "Evidencia del empaque original",
        description: "problem-inactive-original",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/421072870015_inactive_original.jpg",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-16 17:42:06",
      },
      {
        id: "1337",
        name: "Más batman",
        description: "additional-file",
        url: "https://s3.us-east-2.amazonaws.com/envia-staging/uploads/shipments/problems/421072870015_additional_file_20210824T200645.jpeg",
        active: "1",
        visible: "1",
        created_by: "27",
        created_at: "2021-08-24 20:07:12",
      },
    ],
  },
];
export default function Home() {
  const [ticketsList, setTicketsList] = useState(LIST_TEST);

  return (
    <UiContainer fluid>
      <Row className="h-100">
        <Col md={4}>
          <TitleH3>Tickets</TitleH3>
          <TitleH6>Manange the diffrerent ticket options we have</TitleH6>
        </Col>
        <Col md={8} className="h-100">
          <ListTickets data={ticketsList} />
        </Col>
      </Row>
    </UiContainer>
  );
}
